name: Code-Vault Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # gradlew जनरेट करना
      - name: Generate Gradle Wrapper
        run: gradle wrapper

      - name: Grant execute permission
        run: chmod +x gradlew

      # साइनिंग चेक को स्किप करना (-x validateSigningDebug)
      - name: Build Code-Vault APK
        run: ./gradlew assembleDebug -x validateSigningDebug

      - name: Upload Code-Vault APK
        uses: actions/upload-artifact@v4
        with:
          name: Code-Vault
          path: app/build/outputs/apk/debug/app-debug.apk
